/**
 * Memory Writer - Saves decisions and insights to files
 */
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

export class MemoryWriter {

    private getMemoryPath(): string | undefined {
        const workspaceFolders = vscode.workspace.workspaceFolders;
        if (!workspaceFolders) {
            return undefined;
        }
        
        // Look for architecture_memory in workspace root
        const memoryPath = path.join(workspaceFolders[0].uri.fsPath, 'architecture_memory');
        if (fs.existsSync(memoryPath)) {
            return memoryPath;
        }
        
        // Also check if we're inside archi-copilot folder
        const archiCopilotPath = path.join(workspaceFolders[0].uri.fsPath, 'archi-copilot', 'architecture_memory');
        if (fs.existsSync(archiCopilotPath)) {
            return archiCopilotPath;
        }
        
        // Create in workspace root if doesn't exist
        return path.join(workspaceFolders[0].uri.fsPath, 'architecture_memory');
    }

    ensureDirectories(): void {
        const memoryPath = this.getMemoryPath();
        if (!memoryPath) {
            return;
        }

        const dirs = [
            memoryPath,
            path.join(memoryPath, 'static'),
            path.join(memoryPath, 'decisions'),
            path.join(memoryPath, 'insights'),
            path.join(memoryPath, 'politics')
        ];

        for (const dir of dirs) {
            if (!fs.existsSync(dir)) {
                try {
                    fs.mkdirSync(dir, { recursive: true });
                } catch (e) {
                    // Ignore errors
                }
            }
        }
    }

    private getDateString(): string {
        const now = new Date();
        return now.toISOString().split('T')[0];
    }

    private getTimestamp(): string {
        const now = new Date();
        return now.toISOString().replace(/[:.]/g, '-').substring(0, 16);
    }

    private generateFilename(prefix: string, dir: string): string {
        const timestamp = this.getTimestamp();
        return `${timestamp}-${prefix}.md`;
    }

    async saveAsDecision(content: string): Promise<void> {
        const memoryPath = this.getMemoryPath();
        if (!memoryPath) {
            vscode.window.showErrorMessage('No workspace folder open. Cannot save decision.');
            return;
        }

        const decisionsDir = path.join(memoryPath, 'decisions');
        this.ensureDirectories();

        // Ask for a title
        const title = await vscode.window.showInputBox({
            prompt: 'Enter a short title for this decision',
            placeHolder: 'e.g., API Gateway Selection'
        });

        if (!title) {
            return;
        }

        const filename = this.generateFilename('decision', decisionsDir);
        const filePath = path.join(decisionsDir, filename);

        const formattedContent = `---
date: ${this.getDateString()}
type: decision
title: ${title}
status: accepted
---

# Decision: ${title}

${content}

---
*Generated by Archi Copilot*
`;

        try {
            fs.writeFileSync(filePath, formattedContent);
            
            // Open the file for editing
            const doc = await vscode.workspace.openTextDocument(filePath);
            await vscode.window.showTextDocument(doc);

            vscode.window.showInformationMessage(`✅ Decision saved: ${filename}`);
        } catch (e) {
            vscode.window.showErrorMessage(`Failed to save decision: ${e}`);
        }
    }

    async saveAsInsight(content: string): Promise<void> {
        const memoryPath = this.getMemoryPath();
        if (!memoryPath) {
            vscode.window.showErrorMessage('No workspace folder open. Cannot save insight.');
            return;
        }

        const insightsDir = path.join(memoryPath, 'insights');
        this.ensureDirectories();

        // Ask for a title
        const title = await vscode.window.showInputBox({
            prompt: 'Enter a short title for this insight',
            placeHolder: 'e.g., Performance patterns observed'
        });

        if (!title) {
            return;
        }

        const filename = this.generateFilename('insight', insightsDir);
        const filePath = path.join(insightsDir, filename);

        const formattedContent = `---
date: ${this.getDateString()}
type: insight
title: ${title}
---

# Insight: ${title}

${content}

---
*Generated by Archi Copilot*
`;

        try {
            fs.writeFileSync(filePath, formattedContent);
            
            // Open the file for editing
            const doc = await vscode.workspace.openTextDocument(filePath);
            await vscode.window.showTextDocument(doc);

            vscode.window.showInformationMessage(`✅ Insight saved: ${filename}`);
        } catch (e) {
            vscode.window.showErrorMessage(`Failed to save insight: ${e}`);
        }
    }
}
